### ISSUE TITLE
扫码登陆失败

### ISSUE THREAD

**Issue by HaclyonDev** [IAmKrisWu/wechat-ChatGPT#1]
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Traceback (most recent call last):
  File "E:\python源代码\wechatgpt\chat.py", line 119, in <module>
    itchat.auto_login(hotReload=True)
  File "C:\Users\legen\AppData\Local\Programs\Python\Python311\Lib\site-packages\itchat\components\register.py", line 31, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "C:\Users\legen\AppData\Local\Programs\Python\Python311\Lib\site-packages\itchat\components\login.py", line 53, in login
    status = self.check_login()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\legen\AppData\Local\Programs\Python\Python311\Lib\site-packages\itchat\components\login.py", line 137, in check_login
    if process_login_info(self, r.text):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\legen\AppData\Local\Programs\Python\Python311\Lib\site-packages\itchat\components\login.py", line 172, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\legen\AppData\Local\Programs\Python\Python311\Lib\xml\dom\minidom.py", line 2000, in parseString
    return expatbuilder.parseString(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\legen\AppData\Local\Programs\Python\Python311\Lib\xml\dom\expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\legen\AppData\Local\Programs\Python\Python311\Lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: mismatched tag: line 64, column 4

**Comment by HaclyonDev** [comment]
用大号微信还是小号微信都不行
